### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by dstock48**
- Add grid layout for book cards to the search page and club page
- Add styling to the book cards
- Add responsiveness to the grid sections and the header

### CODE REVIEW

**Comment by dstock48** [comment]
uuuummmm, I have no idea why all your old commits are included with this. I did the `git pull --rebase upstream master` command in terminal before uploading this branch to my fork.

**Comment by lindsaywparker** [comment]
I was wondering what all that was!  That was some real old stuff!

Only briefly thinking about it, my best guess is the branch you were
working on was really old, so there have been a ton of commits to master
since then?  If you've been working on the same branch since close to day
1, that's probably do it?

**Comment by dstock48** [comment]
Oh yea, the master branch on my laptop was totally up to date, but the master branch on my fork was probably really behind 😖

**Comment by lindsaywparker** [comment]
Doh!

**Pull request closed without merging**
